function f = f(in1,in2)
%F
%    F = F(IN1,IN2,DT)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    15-May-2018 21:37:18
% Constants
dt = 1e-3;  % Time step

u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
t2 = cos(x8);
t3 = sin(x7);
t4 = cos(x7);
t5 = sin(x8);
f = [x1+dt.*x4;x2+dt.*x5;x3+dt.*x6;x4+dt.*u1;x5+dt.*u2;x6+dt.*u3;x7+dt.*x9;x8+dt.*x10;x9-dt.*(t2.*t3.*(9.81e2./2.0e2)-t4.*u1.*(1.0./2.0)+t3.*t4.*x10.^2+t2.*t3.*u3.*(1.0./2.0)-t3.*t5.*u2.*(1.0./2.0));x10-(dt.*(t5.*(9.81e2./1.0e2)+t2.*u2+t5.*u3-t3.*x9.*x10.*4.0).*(1.0./2.0))./t4];
