function h = h(in1)
%H
%    H = H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    15-May-2018 21:51:29

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x7 = in1(7,:);
x8 = in1(8,:);
h = [x1;x2;x3;0.0;0.0;0.0;x7;x8;0.0;0.0];
