function H = hJacobian(in1)
%HJACOBIAN
%    H = HJACOBIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    15-May-2018 21:51:29

H = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[10,3]);
